# Redes Neuronales Básicas

### Práctica de Machine Learning y Deep Learning

En esta práctica se implementan diferentes modelos de redes neuronales
artificiales utilizando Python y NumPy, sin utilizar librerías especializadas
de Deep Learning.

Se desarrollan un perceptrón, una red neuronal de una capa y una red neuronal
multicapa, con el objetivo de comprender el procesamiento matemático,
la vectorización, la propagación hacia adelante y el proceso de aprendizaje
mediante actualización de pesos.

1. Introducción

Las redes neuronales artificiales son modelos computacionales inspirados
en el funcionamiento de las neuronas biológicas. Estas permiten procesar
datos mediante operaciones matemáticas realizadas sobre entradas, pesos
y sesgos.

En esta práctica se implementan modelos neuronales desde cero utilizando
Python y NumPy. El objetivo es comprender cómo una red neuronal procesa
información, genera predicciones y modifica sus parámetros durante el
entrenamiento.

Se trabajará con un perceptrón, una red neuronal de una capa y una red
neuronal multicapa (Vanilla).

2. Importación de NumPy

NumPy es una biblioteca de Python utilizada para realizar operaciones
matemáticas y trabajar eficientemente con arreglos y matrices.

En esta práctica NumPy permite realizar productos matriciales, operaciones
vectorizadas y cálculos necesarios para implementar las redes neuronales.

In [2]:
import numpy as np

print("NumPy importado correctamente")

NumPy importado correctamente


3. Operaciones básicas con NumPy

Las redes neuronales utilizan operaciones matemáticas con vectores y
matrices para procesar los datos.

A continuación se muestran algunas operaciones básicas de NumPy que
serán utilizadas posteriormente en los modelos neuronales.

In [3]:
# Crear un vector
vector = np.array([1, 2, 3])

# Crear una matriz
matriz = np.array([
    [1, 2],
    [3, 4]
])

# Multiplicación de matrices
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

resultado = A @ B

print("Vector:")
print(vector)

print("\nMatriz:")
print(matriz)

print("\nResultado de la multiplicación matricial:")
print(resultado)

Vector:
[1 2 3]

Matriz:
[[1 2]
 [3 4]]

Resultado de la multiplicación matricial:
[[19 22]
 [43 50]]


4. Implementación de un Perceptrón

El perceptrón es uno de los modelos más sencillos de una red neuronal
artificial.

Recibe diferentes entradas, las multiplica por sus respectivos pesos,
suma un sesgo (bias) y posteriormente aplica una función de activación.

La operación principal es:

Z = X · W + b

Posteriormente se utiliza una función escalón para convertir el resultado
en una salida binaria de 0 o 1.

Para esta implementación se utilizará la compuerta lógica AND.

In [4]:
import numpy as np

# Datos de entrada para la compuerta AND
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Resultados correctos esperados
y = np.array([0, 0, 0, 1])

# Pesos iniciales
W = np.array([0.0, 0.0])

# Bias inicial
b = 0.0

# Tasa de aprendizaje
tasa_aprendizaje = 0.1

# Número de veces que recorreremos todos los datos
epocas = 10


# Función de activación
def funcion_escalon(z):
    if z >= 0:
        return 1
    else:
        return 0


# Entrenamiento
for epoca in range(epocas):

    print(f"\nÉpoca {epoca + 1}")

    # Recorremos cada entrada y su resultado esperado
    for entradas, esperado in zip(X, y):

        # Calculamos la suma ponderada
        Z = entradas @ W + b

        # Calculamos la predicción
        prediccion = funcion_escalon(Z)

        # Calculamos el error
        error = esperado - prediccion

        # Actualizamos los pesos
        W = W + tasa_aprendizaje * error * entradas

        # Actualizamos el bias
        b = b + tasa_aprendizaje * error

        print(
            f"Entrada: {entradas} | "
            f"Esperado: {esperado} | "
            f"Predicción: {prediccion} | "
            f"Error: {error}"
        )


print("\nPesos finales:", W)
print("Bias final:", b)


Época 1
Entrada: [0 0] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [0 1] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 1] | Esperado: 1 | Predicción: 0 | Error: 1

Época 2
Entrada: [0 0] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [0 1] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [1 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 1] | Esperado: 1 | Predicción: 0 | Error: 1

Época 3
Entrada: [0 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [0 1] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [1 0] | Esperado: 0 | Predicción: 1 | Error: -1
Entrada: [1 1] | Esperado: 1 | Predicción: 0 | Error: 1

Época 4
Entrada: [0 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [0 1] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 0] | Esperado: 0 | Predicción: 0 | Error: 0
Entrada: [1 1] | Esperado: 1 | Predicción: 1 | Error: 0

Época 5
Entrada: [0 0] | Esperado: 0 | Predicción: 0 | Error: 

Comprobación de las predicciones

Después del entrenamiento se realizan nuevamente las predicciones para
comprobar si el perceptrón aprendió correctamente la función lógica AND.


In [5]:
# Comprobación de las predicciones finales

print("Predicciones finales del perceptrón:")

for entradas in X:
    Z = entradas @ W + b
    prediccion = funcion_escalon(Z)

    print(f"Entrada: {entradas} -> Predicción: {prediccion}")

Predicciones finales del perceptrón:
Entrada: [0 0] -> Predicción: 0
Entrada: [0 1] -> Predicción: 0
Entrada: [1 0] -> Predicción: 0
Entrada: [1 1] -> Predicción: 1


5. Red neuronal de una capa

Una red neuronal de una capa está formada por una capa de neuronas que
recibe los datos de entrada y genera una salida.

En este modelo se utilizan operaciones matriciales para procesar
simultáneamente los diferentes ejemplos.

La operación principal es:

Z = X · W + b

Posteriormente se aplica una función de activación para obtener las
predicciones.

El uso de operaciones matriciales permite aplicar el concepto de
vectorización, evitando realizar manualmente cada cálculo individual.

In [6]:
# Red neuronal de una capa

import numpy as np

# Datos de entrada
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Resultados esperados
y = np.array([0, 0, 0, 1])

# Pesos de la red
W = np.array([
    [0.5],
    [0.5]
])

# Bias
b = np.array([[-0.7]])

# Propagación hacia adelante
Z = X @ W + b

# Función de activación escalón
A = (Z >= 0).astype(int)

print("Valores de Z:")
print(Z)

print("\nPredicciones:")
print(A)

Valores de Z:
[[-0.7]
 [-0.2]
 [-0.2]
 [ 0.3]]

Predicciones:
[[0]
 [0]
 [0]
 [1]]


6. Red neuronal multicapa (Vanilla)

Una red neuronal multicapa está formada por una capa de entrada, una o más
capas ocultas y una capa de salida.

En esta implementación se utiliza una capa oculta compuesta por tres
neuronas y una neurona en la capa de salida.

La información se procesa mediante propagación hacia adelante (Forward
Propagation).

La primera operación calcula la salida de la capa oculta:

Z1 = X · W1 + b1

Después se aplica la función de activación:

A1 = Sigmoid(Z1)

Posteriormente se calcula la salida final:

Z2 = A1 · W2 + b2

Y nuevamente se aplica la función Sigmoid:

A2 = Sigmoid(Z2)

La implementación se realiza desde cero utilizando Python y NumPy,
sin utilizar librerías especializadas de Deep Learning.

In [7]:
# Red neuronal multicapa desde cero

import numpy as np

# Datos de entrada
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Pesos entre la entrada y la capa oculta
W1 = np.array([
    [0.5, 0.3, 0.2],
    [0.4, 0.6, 0.1]
])

# Bias de la capa oculta
b1 = np.array([0.1, 0.1, 0.1])

# Pesos entre la capa oculta y la capa de salida
W2 = np.array([
    [0.5],
    [0.4],
    [0.6]
])

# Bias de la capa de salida
b2 = np.array([0.1])


# Función de activación Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# Propagación hacia adelante - capa oculta
Z1 = X @ W1 + b1
A1 = sigmoid(Z1)

# Propagación hacia adelante - capa de salida
Z2 = A1 @ W2 + b2
A2 = sigmoid(Z2)

print("Salida de la capa oculta:")
print(A1)

print("\nSalida de la red neuronal:")
print(A2)

Salida de la capa oculta:
[[0.52497919 0.52497919 0.52497919]
 [0.62245933 0.66818777 0.549834  ]
 [0.64565631 0.59868766 0.57444252]
 [0.73105858 0.73105858 0.59868766]]

Salida de la red neuronal:
[[0.70836754]
 [0.73270792]
 [0.73242651]
 [0.75346253]]


7. Entrenamiento de la red neuronal multicapa

Para demostrar el proceso de aprendizaje de una red multicapa se utiliza
la operación lógica XOR.

A diferencia de AND, XOR requiere una estructura neuronal con una capa
oculta para poder representar correctamente la relación entre las entradas
y las salidas.

El entrenamiento se realiza mediante:

1. Propagación hacia adelante.
2. Cálculo del error.
3. Retropropagación (Backpropagation).
4. Actualización de los pesos y sesgos.
5. Repetición del proceso durante varias épocas.

La red utiliza la función Sigmoid como función de activación.

In [8]:
import numpy as np

# Datos de entrada para XOR
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Resultados esperados
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Semilla para obtener resultados reproducibles
np.random.seed(42)

# Pesos de la capa de entrada a la capa oculta
W1 = np.random.randn(2, 3)

# Bias de la capa oculta
b1 = np.zeros((1, 3))

# Pesos de la capa oculta a la capa de salida
W2 = np.random.randn(3, 1)

# Bias de la capa de salida
b2 = np.zeros((1, 1))

# Tasa de aprendizaje
tasa_aprendizaje = 0.5

# Número de épocas
epocas = 10000


# Función de activación Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# Derivada de Sigmoid
def sigmoid_derivada(a):
    return a * (1 - a)


# Entrenamiento
for epoca in range(epocas):

    # PROPAGACIÓN HACIA ADELANTE

    Z1 = X @ W1 + b1
    A1 = sigmoid(Z1)

    Z2 = A1 @ W2 + b2
    A2 = sigmoid(Z2)

    # CÁLCULO DEL ERROR

    error = y - A2

    # RETROPROPAGACIÓN

    dZ2 = error * sigmoid_derivada(A2)

    dW2 = A1.T @ dZ2
    db2 = np.sum(dZ2, axis=0, keepdims=True)

    dA1 = dZ2 @ W2.T
    dZ1 = dA1 * sigmoid_derivada(A1)

    dW1 = X.T @ dZ1
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    # ACTUALIZACIÓN DE PESOS

    W2 = W2 + tasa_aprendizaje * dW2
    b2 = b2 + tasa_aprendizaje * db2

    W1 = W1 + tasa_aprendizaje * dW1
    b1 = b1 + tasa_aprendizaje * db1


# PREDICCIONES FINALES

Z1 = X @ W1 + b1
A1 = sigmoid(Z1)

Z2 = A1 @ W2 + b2
A2 = sigmoid(Z2)

predicciones = (A2 >= 0.5).astype(int)

print("Resultados finales:")

print("\nValores reales:")
print(y)

print("\nPredicciones:")
print(predicciones)

print("\nProbabilidades:")
print(A2)

Resultados finales:

Valores reales:
[[0]
 [1]
 [1]
 [0]]

Predicciones:
[[0]
 [1]
 [1]
 [0]]

Probabilidades:
[[0.00726458]
 [0.98314391]
 [0.98363782]
 [0.02171897]]


8. Conclusiones

Durante esta práctica se implementaron diferentes modelos de redes
neuronales utilizando únicamente Python y NumPy, permitiendo comprender
los fundamentos matemáticos involucrados en su funcionamiento.

La implementación del perceptrón permitió comprender la relación entre
las entradas, los pesos, el bias, la función de activación y el proceso
de actualización de los parámetros durante el aprendizaje.

La red neuronal de una capa permitió trabajar con matrices y operaciones
vectorizadas, demostrando la importancia de NumPy para realizar
eficientemente los cálculos matemáticos utilizados en inteligencia
artificial.

Finalmente, mediante la implementación de una red neuronal multicapa
se pudo observar el proceso de propagación hacia adelante y el
entrenamiento mediante retropropagación. La red logró aprender
correctamente la función lógica XOR, obteniendo las predicciones
esperadas para los cuatro casos de prueba.

La práctica permitió comprender de manera más profunda el funcionamiento
interno de las redes neuronales y la importancia de conceptos como
vectorización, funciones de activación, pesos, sesgos y backpropagation,
sin depender de librerías especializadas de Deep Learning.